server:
  port: 9001

spring:
  application:
    name: consumer_9001

eureka:
  instance:
    instance-id: dept-consumer-9001  #自定义服务别名
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


feign:
  hystrix:
    enabled: true
