server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false #是否从Eureka中获取注册信息
    register-with-eureka: false #是否将自己注册到Eureka服务中，本身所以无需注册
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

