server:
  port: 8001

spring:
  application:
    name: CLOUD-DEPT-SERVER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: bVWVvJrazamoDooz34Zc6J5QBI544VqyJctT0rqM14wHPyZDTdhVEHxSVFc6axLchAAWXqbaRJ6hzfI6OSBLZQ==
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 5
      filter:
        config:
          enabled: true
      connect-properties: {config.decrypt: true,config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIvHR1B97vSJehrT5ZCdtpYAPIOrsyzA0rU7TqfTTp/MuzxmTT2Dwo37hl3y3UxYT4DDdTELYrAiN/KFwGh/FZECAwEAAQ==}

mybatis:
  type-aliases-package: com.hui.entity
logging:
  level:
    com.hui.mapper: DEBUG

eureka:
  instance:
    instance-id: dept-server-8001  #自定义服务别名
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
