server:
  port: 5001

spring:
  application:
    name: cloud-zuul-5001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: zuul-5001
    prefer-ip-address: true

zuul:
#  ignored-patterns: /cloud-dept-server/** #排除某个url
  prefix: /hui              #设置访问前缀
  ignored-services: "*"     #排除所有url
  routes:
    mydept:        #传统的路由配置,此名称可以自定义
      serviceId: CLOUD-DEPT-SERVER   #映射的url
      path: /mydept/**               #被映射的url

