server:
  port: 3344
spring:
  application:
    name: cloud-config-server-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lanceff/springcloud_project.git # git仓库的地址
          search-paths: spring-cloud-configs  # 配置文件存储在仓库子目录中
          default-label: master
          username: Lanceff
          password: